// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetRS.Data;

namespace VetRS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "4853db81-591a-4685-8dce-81e57d407831",
                            ConcurrencyStamp = "bbe3e3d0-9053-45cd-acf7-5d8d3a70f9dd",
                            Name = "Veteran",
                            NormalizedName = "VETERAN"
                        },
                        new
                        {
                            Id = "127bd18b-f101-48c8-9b6a-dd607d67715d",
                            ConcurrencyStamp = "c52e1bb3-d178-427e-b5ec-cee55b0645ee",
                            Name = "VSO",
                            NormalizedName = "VSO"
                        },
                        new
                        {
                            Id = "9db28102-8654-44e1-a73b-34720c581570",
                            ConcurrencyStamp = "ca7f6561-36d3-41b1-8ab1-eb167aaf101e",
                            Name = "Education Rep.",
                            NormalizedName = "EDUCATION REP"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("VetRS.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EducationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationZipCode")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramBio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramImageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Education");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationCity = "Milwaukee",
                            EducationState = "Wisconsin",
                            EducationStreet = "Mitchell St.",
                            EducationZipCode = 53215,
                            Email = "BigGuy@comcast.net",
                            FirstName = "Bobby",
                            ImageLocation = "",
                            LastName = "Knight",
                            Lat = 43.012317000000003,
                            Long = -87.955793999999997,
                            PhoneNumber = "2228389992",
                            ProgramBio = "Wisconsin's Premier Educational State Institution",
                            ProgramImageLocation = "",
                            ProgramName = "University of Wisconsin"
                        },
                        new
                        {
                            Id = 2,
                            EducationCity = "Milwaukee",
                            EducationState = "Wisconsin",
                            EducationStreet = "700 W. State Street",
                            EducationZipCode = 53233,
                            Email = "RuReady@comcast.net",
                            FirstName = "Mitch",
                            ImageLocation = "",
                            LastName = "Holcomb",
                            Lat = 43.043551000000001,
                            Long = -87.921150999999995,
                            PhoneNumber = "9392244234",
                            ProgramBio = "Education that transforms lives, industry, and community.",
                            ProgramImageLocation = "",
                            ProgramName = "Milwaukee Area Technical College"
                        },
                        new
                        {
                            Id = 3,
                            EducationCity = "Milwaukee",
                            EducationState = "Wisconsin",
                            EducationStreet = "6801 N. Yates Road",
                            EducationZipCode = 53217,
                            Email = "ShellieN19@gmail.com",
                            FirstName = "Sheila",
                            ImageLocation = "",
                            LastName = "Williams",
                            Lat = 43.140320000000003,
                            Long = -87.907152999999994,
                            PhoneNumber = "8003478822",
                            ProgramBio = "Stritch's story is integrated with more than 38,000 of our alumni who are positively impacting the communities in which they live, work, serve, and lead.",
                            ProgramImageLocation = "",
                            ProgramName = "Cardinal Stritch University"
                        },
                        new
                        {
                            Id = 4,
                            EducationCity = "Milwaukee",
                            EducationState = "Wisconsin",
                            EducationStreet = "313 N Plankinton Ave Suite 209",
                            EducationZipCode = 53203,
                            Email = "Wendydev13@comcast.net",
                            FirstName = "Wendy",
                            ImageLocation = "",
                            LastName = "Knight",
                            Lat = 43.034196000000001,
                            Long = -87.912329999999997,
                            PhoneNumber = "4145330639",
                            ProgramBio = "devCodeCamp has been awarded 'Best Coding Bootcamp' by Course Report each year 2016-2020",
                            ProgramImageLocation = "",
                            ProgramName = "devCodeCamp"
                        },
                        new
                        {
                            Id = 5,
                            EducationCity = "Milwaukee",
                            EducationState = "Wisconsin",
                            EducationStreet = "Mellencamp Hall, Room 168A, P.O. Box 469",
                            EducationZipCode = 53211,
                            Email = "vets@uwm.edu",
                            FirstName = "James",
                            ImageLocation = "",
                            LastName = "Schmidt",
                            Lat = 43.074987999999998,
                            Long = -87.879599999999996,
                            PhoneNumber = "4142296627",
                            ProgramBio = "Wisconsin's Premier Educational State Institution",
                            ProgramImageLocation = "",
                            ProgramName = "University of Wisconsin - Milwaukee"
                        });
                });

            modelBuilder.Entity("VetRS.Models.MilitaryJobTranslator", b =>
                {
                    b.Property<string>("MilitarySpecialtyNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CivilianJobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilitaryJobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MilitarySpecialtyNumber");

                    b.ToTable("MilitaryJobsTranslator");

                    b.HasData(
                        new
                        {
                            MilitarySpecialtyNumber = "3531",
                            CivilianJobTitle = "Truck Driver",
                            MilitaryJobTitle = "Motor Vehicle Operator"
                        },
                        new
                        {
                            MilitarySpecialtyNumber = "8411",
                            CivilianJobTitle = "Human Resource Specialist",
                            MilitaryJobTitle = "Recruiter"
                        },
                        new
                        {
                            MilitarySpecialtyNumber = "25B",
                            CivilianJobTitle = "Computer and Information System Manager",
                            MilitaryJobTitle = "Information Technology Specialist"
                        },
                        new
                        {
                            MilitarySpecialtyNumber = "4N0",
                            CivilianJobTitle = "Emergency Medical Technician",
                            MilitaryJobTitle = "Aerospace Medical Services"
                        },
                        new
                        {
                            MilitarySpecialtyNumber = "4T0",
                            CivilianJobTitle = "Clinical Laboratory Technologist",
                            MilitaryJobTitle = "Medical Laboratory Specialist"
                        });
                });

            modelBuilder.Entity("VetRS.Models.VSO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("VSOCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VSOState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VSOStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VSOZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("VSO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Lombardibarbie@PackersChamps.com",
                            FirstName = "Aaron",
                            ImageLocation = "",
                            LastName = "Rodgers",
                            Lat = 43.066527000000001,
                            Long = -87.914071000000007,
                            PhoneNumber = "9205552020",
                            Rating = 5,
                            VSOCity = "Milwaukee",
                            VSOState = "WI",
                            VSOStreet = "Martin Luther King Dr.",
                            VSOZipCode = 53212
                        },
                        new
                        {
                            Id = 2,
                            Email = "Gunslinger@PackersChamps.com",
                            FirstName = "Brett",
                            ImageLocation = "",
                            LastName = "Farve",
                            Lat = 43.061504999999997,
                            Long = -87.918490000000006,
                            PhoneNumber = "9203332020",
                            Rating = 4,
                            VSOCity = "Milwaukee",
                            VSOState = "WI",
                            VSOStreet = "6th St.",
                            VSOZipCode = 53212
                        },
                        new
                        {
                            Id = 3,
                            Email = "MrHands@PackersChamps.com",
                            FirstName = "Jordy",
                            ImageLocation = "",
                            LastName = "Nelson",
                            Lat = 43.076442,
                            Long = -87.952108999999993,
                            PhoneNumber = "5558675309",
                            Rating = 3,
                            VSOCity = "Milwaukee",
                            VSOState = "WI",
                            VSOStreet = "31st St.",
                            VSOZipCode = 53216
                        },
                        new
                        {
                            Id = 4,
                            Email = "Doubleyourdoublecheck@PackersChamps.com",
                            FirstName = "BJ",
                            ImageLocation = "",
                            LastName = "Raji",
                            Lat = 43.072878000000003,
                            Long = -87.939920000000001,
                            PhoneNumber = "5552344545",
                            Rating = 4,
                            VSOCity = "Milwaukee",
                            VSOState = "Wisconsin",
                            VSOStreet = "22nd St.",
                            VSOZipCode = 53206
                        },
                        new
                        {
                            Id = 5,
                            Email = "Astarrisborn@packerschamps.com",
                            FirstName = "Bart",
                            ImageLocation = "",
                            LastName = "Starr",
                            Lat = 43.065750000000001,
                            Long = -87.933822000000006,
                            PhoneNumber = "5558761515",
                            Rating = 5,
                            VSOCity = "Milwaukee",
                            VSOState = "WI",
                            VSOStreet = "17th St.",
                            VSOZipCode = 53206
                        });
                });

            modelBuilder.Entity("VetRS.Models.Veteran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeteranCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeteranState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeteranStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VeteranZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Veteran");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Sgtjosetorres@yahoo.com",
                            FirstName = "Jose",
                            ImageLocation = "",
                            LastName = "Torres",
                            Lat = 43.459986999999998,
                            Long = -88.819759000000005,
                            PhoneNumber = "9203827037",
                            VeteranCity = "Beaver Dam",
                            VeteranState = "WI",
                            VeteranStreet = "515 Walnut St",
                            VeteranZipCode = 53916
                        },
                        new
                        {
                            Id = 2,
                            Email = "Thatdude@softwaredeveloper.com",
                            FirstName = "Eric",
                            ImageLocation = "",
                            LastName = "Hill",
                            Lat = 43.041615,
                            Long = -87.936449999999994,
                            PhoneNumber = "5552452010",
                            VeteranCity = "Milwaukee",
                            VeteranState = "WI",
                            VeteranStreet = "Kilbourn Ave",
                            VeteranZipCode = 53233
                        },
                        new
                        {
                            Id = 3,
                            Email = "Realamericanhero@DevDogg.com",
                            FirstName = "Chesty",
                            ImageLocation = "",
                            LastName = "Puller",
                            Lat = 43.038843999999997,
                            Long = -87.905073999999999,
                            PhoneNumber = "1234567891",
                            VeteranCity = "Milwaukee",
                            VeteranState = "WI",
                            VeteranStreet = "W. Wisconsin Ave.",
                            VeteranZipCode = 53202
                        },
                        new
                        {
                            Id = 4,
                            Email = "MedalOfHonor@armyman.com",
                            FirstName = "Lucian",
                            ImageLocation = "",
                            LastName = "Adams",
                            Lat = 43.043458999999999,
                            Long = -87.909976,
                            PhoneNumber = "9201119999",
                            VeteranCity = "Milwaukee",
                            VeteranState = "WI",
                            VeteranStreet = "E. State St.",
                            VeteranZipCode = 53202
                        },
                        new
                        {
                            Id = 5,
                            Email = "RealFlyBoy@airforcehero.com",
                            FirstName = "Steven",
                            ImageLocation = "",
                            LastName = "Bennet",
                            Lat = 43.046976999999998,
                            Long = -87.906662999999995,
                            PhoneNumber = "9998883333",
                            VeteranCity = "Milwaukee",
                            VeteranState = "WI",
                            VeteranStreet = "E. Knapp St.",
                            VeteranZipCode = 53202
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetRS.Models.Education", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");
                });

            modelBuilder.Entity("VetRS.Models.VSO", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");
                });

            modelBuilder.Entity("VetRS.Models.Veteran", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
